command_timeout = 1000

[directory]
read_only = ' '

[docker_context]
symbol = ' '

[git_status]
style = 'bold blue'
conflicted = '[=${count}](bold red)'
stashed = '\$${count}'
deleted = '[✘ ${count}](bold red)'
renamed = '[»${count}](bold yellow)'
modified = '!${count}'
staged = '[+${count}](bold yellow)'
untracked = '?${count}'
ahead = '${count}'
behind = '[${count}](bold cyan)'

[lua]
symbol = ' '

[python]
symbol = ' '

[java]
symbol = ' '

[perl]
symbol = ' '
