#! /bin/sh

###################
# Keyboard Layout #
###################
setxkbmap fr


########################
# Launch hotkey daemon #
########################
pgrep -x sxhkd > /dev/null || sxhkd &


##########################
# Monitors and statusbar #
##########################
killall -q polybar
bspc config top_padding 0
bspc config bottom_padding 0
if  xrandr | grep -q "HDMI-1-0 c"; then
    xrandr --output "HDMI-1-0" --above "eDP-1" --auto
    bspc monitor "eDP-1" -d 1 2 3
    bspc monitor "HDMI-1-0" -d 4 5 6 7 8 9 10
    polybar --reload -c ~/.config/polybar/config.ini top_bar &
    polybar --reload -c ~/.config/polybar/config.ini bottom_bar &
else
    xrandr --output "HDMI-1-0" --off
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
    polybar --reload -c ~/.config/polybar/config.ini mainbar &
fi


###########
# Borders #
###########
bspc config border_width 1
bspc config focused_border_color '#9d7cd8'


########
# Gaps #
########
bspc config window_gap 10


##########
# Splits #
##########
bspc config split_ratio 0.5


#########
# Focus #
#########
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true


##############
# Compositor #
##############
picom &


#########
# Rules #
#########
bspc rule -a Spotify desktop='10'
bspc rule -a discord desktop='9'
bspc rule -a Thunderbird desktop='8'
bspc rule -a zoom desktop='7'

bspc rule -a Galculator state=floating
bspc rule -a Gpick state=floating
bspc rule -a Font-manager state=floating
bspc rule -a qt5ct state=floating
bspc rule -a lxappearance state=floating
bspc rule -a Pavucontrol state=floating

bspc rule -a Zathura state=tiled
bspc rule -a jetbrains-toolbox state=tiled


#############
# Autostart #
#############
numlockx on
xset r rate 220 35
setxkbmap -option caps:swapescape
feh --bg-fill /misc/yes.jpg &
pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x spotify > /dev/null || spotify &
pgrep -x discord > /dev/null || discord &
pgrep -x thunderbird > /dev/null || thunderbird &
pgrep -x flameshot > /dev/null || flameshot &
